### ISSUE TITLE
Jobs section

### ISSUE THREAD

**Issue by dmarti** [globalprivacycontrol/landing-page#22]
Right now there is 1 open job posting mentioning GPC: https://cafemedia.applytojob.com/apply/iwvoZVQng8/Product-Manager-Data-Privacy-Compliance?referrer=2021041618150950ZTZSCECR1AGHKF

Does it make sense to add a jobs section to the site, either now or in the future when multiple job posts have GPC as a required/desired skill?

**Comment by asoltani** [comment]
Thanks for suggesting @dmarti 
Perhaps once we see a significant number of these we can consider dedicating the real estate
