### ISSUE TITLE
Spec link no longer works

### ISSUE THREAD

**Issue by bdougherty** [globalprivacycontrol/landing-page#39]
Linked to from the readme and https://globalprivacycontrol.org/#gpc-spec:

https://globalprivacycontrol.github.io/gpc-spec

Generates a "Site not found" error.

**Comment by SebastianZimmeck** [comment]
Thank you, @bdougherty! Should be fixed soon.

**Comment by dharb** [comment]
Spec links are now fixed, thanks for flagging @bdougherty!
