### ISSUE TITLE
Add Didomi to org page

### ISSUE THREAD

**Issue by SebastianZimmeck** [globalprivacycontrol/landing-page#42]
As Didomi is also supporting GPC, let's add their logo to the [org section](https://globalprivacycontrol.org/#orgs).

![Didomi_Logo_1000x1000](https://user-images.githubusercontent.com/11034003/222537252-1bc2eecd-5f07-402e-8a10-2771b6fa5ff8.png)

**Comment by SebastianZimmeck** [comment]
OK, I realize that we have not used logos for the other CMPs. So, we would not use a logo for Didomi either. It would be in the same style as the other CMPs.

**Comment by dharb** [comment]
@SebastianZimmeck is there a specific page we should link to for Didomi, or just https://www.didomi.io/ ?

**Comment by SebastianZimmeck** [comment]
Just https://www.didomi.io/ will do.
