### ISSUE TITLE
Dead FAQ Link

### ISSUE THREAD

**Issue by SVendittelli** [globalprivacycontrol/landing-page#69]
One of the links in the Frequently Asked Questions section on the homepage leads to a non-functioning site. I do not know how to contact the owner of the other site to ask them to update. Should it instead link to <https://globalprivacycontrol.org/implementation> now?

https://github.com/globalprivacycontrol/landing-page/blob/89fa395eba56070a4e30392f1d6835f25c5f8aa6/content/faq.md?plain=1#L62

<img width="1128" alt="Screenshot 2023-12-26 084943" src="https://github.com/globalprivacycontrol/landing-page/assets/17616742/9e73a68d-21be-4cf4-a7ae-ca019171fce6">

**Comment by SebastianZimmeck** [comment]
Thanks, @SVendittelli! 

It looks like our sample implementation stopped running. We will fix that.

**Comment by dharb** [comment]
Thanks for letting us know! Looks like Glitch deprecated the version of node we were using on our reference implementation. Updated and working again.
