### ISSUE TITLE
Add For Users page

### ISSUE THREAD

**Issue by moates** [globalprivacycontrol/landing-page#75]
As discussed in the group meetings, we want to add a simple explainer for users.

My suggestions for this change would be: 
* create a new page "GPC for Everyday People"
* in navbar, "Implementation" -> "For Implementers"
* in navbar, add "For Users" to navigate to the new explainer page
* in FAQs, change the link in "More information about downloading GPC is available here." to point to new explainer page

I'm attaching the basic page content to get started that already received feedback from the group. I'm happy to try and take a stab at a PR. But if anyone has capacity, that would be preferable because i've never used any of this tooling & my npm build fails when I try to build this locally. 

[GPC for everyday people (3).pdf](https://github.com/globalprivacycontrol/landing-page/files/15340322/GPC.for.everyday.people.3.pdf)
[for-users.md.txt](https://github.com/globalprivacycontrol/landing-page/files/15340323/for-users.md.txt)
.

**Comment by SebastianZimmeck** [comment]
I implemented a simple version of the user guide just pointing from the navbar "For Users" to the pdf @moates provided. Pointing straight to the pdf works for me, but if you, @moates or @dharb, feel differently, we can also create a dedicated user site similar to the implementer site. The changes are in branch [issue-75](https://github.com/globalprivacycontrol/landing-page/tree/issue-75). Here is a screenshot. Clicking on "For Users" will bring up the pdf of @moates.
 
<img width="1278" alt="Screenshot 2024-07-07 at 3 03 17 PM" src="https://github.com/globalprivacycontrol/landing-page/assets/11034003/29a21529-4eb7-427f-b08e-6ec5d46875fc">

I have a few suggestions for the text of the pdf and attach a revised version below. What do you think, @moates? Can you create an updated pdf of how you see fit? 
- "to better respect your privacy." -> "to respect your privacy."
- "can exercise your legal right to opt out" -> "will exercise your legal right to opt out"
- "some sites are legally bound to respect" -> "many sites are legally bound to respect"
- The What does GPC *not* do?/Downsides/Fingerprinting sections are bit too extensive for my taste. Can we shorten that to one or two sentences? Omit the fingerprinting risk as that is really really low. Maybe, just say something along the lines of "GPC does not work on all sites (we are working on it!) and is not a replacement for a tracking/ad blocker but instead helps you to exercise your legal rights to opt out." or something similar?
- Also, what should go into the placeholder in the pdf?

[for-users.md.txt](https://github.com/user-attachments/files/16120432/for-users.md.txt)

**Comment by SebastianZimmeck** [comment]
@moates, can you make these changes or send me the document to edit?

**Comment by SebastianZimmeck** [comment]
Here is the [Google Doc with an editable version of the text](https://docs.google.com/document/d/1mry7TGWw1_IsMpfPUn9NulPi6vbPz7rOMlNBDprN5C8/edit?usp=sharing).
