### ISSUE TITLE
Update next.config.js to run site locally?

### ISSUE THREAD

**Issue by SebastianZimmeck** [globalprivacycontrol/landing-page#79]
@dharb, I wanted to run the site locally and got the following error:

<img width="845" alt="Screenshot 2024-07-07 at 2 40 26 PM" src="https://github.com/globalprivacycontrol/landing-page/assets/11034003/37e74399-7584-4283-b16b-870b2b901857">

Then, in the [next.config.js](https://github.com/globalprivacycontrol/landing-page/blob/ca937c74926eb6716c08ac976e69749dc80810ab/next.config.js#L11) I removed the line `output: 'export'`, and it worked. Should we remove this line? 

For the time being, I left the next.config.js as is because I was not sure if this is a local setup issue on my end or a general issue.

**Comment by dharb** [comment]
@SebastianZimmeck can you use `npm run dev` for local development instead? Switching to use `output: export` was a side effect of bumping Next.js to v14.1.1 to resolve a dependabot issue in https://github.com/globalprivacycontrol/landing-page/pull/71

**Comment by SebastianZimmeck** [comment]
Thanks, @dharb! That worked! I updated the readme accordingly.

**Comment by dharb** [comment]
Thanks @SebastianZimmeck for updating the readme!
